services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - toolsnet
    ports:
      - 9069:9090
    restart: unless-stopped
    volumes:
      - ./config/prometheus/:/etc/prometheus
      - ./data/prometheus:/prometheus
      - ./logs/prometheus:/var/log/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    networks:
      - toolsnet
    ports:
      - 3069:3000
    restart: unless-stopped
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./data/grafana:/var/lib/grafana
      - ./logs/grafana:/var/log/grafana
networks:
  toolsnet:
    external: true
